let fonts = [
  "ABeeZee",
  "Alegreya",
  "Alegreya SC",
  "Alegreya Sans",
  "Alegreya Sans SC",
  "Aleo",
  "Almendra",
  "Alumni Sans",
  "Amaranth",
  "Amiri",
  "Andada Pro",
  "Andika New Basic",
  "Anonymous Pro",
  "Arapey",
  "Archivo",
  "Archivo Narrow",
  "Arimo",
  "Arsenal",
  "Arvo",
  "Asap",
  "Asap Condensed",
  "Atkinson Hyperlegible",
  "Averia Libre",
  "Averia Sans Libre",
  "Averia Serif Libre",
  "Azeret Mono",
  "B612",
  "B612 Mono",
  "Bai Jamjuree",
  "Balsamiq Sans",
  "Barlow",
  "Barlow Condensed",
  "Barlow Semi Condensed",
  "Baskervville",
  "Be Vietnam",
  "Be Vietnam Pro",
  "Bellota",
  "Bellota Text",
  "Besley",
  "Bitter",
  "Bodoni Moda",
  "Bona Nova",
  "Brygada 1918",
  "Cabin",
  "Caladea",
  "Cambay",
  "Cantarell",
  "Cardo",
  "Castoro",
  "Caudex",
  "Chakra Petch",
  "Changa One",
  "Chau Philomene One",
  "Chivo",
  "Comic Neue",
  "Cormorant",
  "Cormorant Garamond",
  "Cormorant Infant",
  "Courier Prime",
  "Cousine",
  "Crete Round",
  "Crimson Pro",
  "Crimson Text",
  "Cuprum",
  "DM Mono",
  "DM Sans",
  "DM Serif Display",
  "DM Serif Text",
  "EB Garamond",
  "Economica",
  "Epilogue",
  "Exo",
  "Exo 2",
  "Expletus Sans",
  "Fahkwang",
  "Fanwood Text",
  "Faustina",
  "Fira Sans",
  "Fira Sans Condensed",
  "Fira Sans Extra Condensed",
  "Fondamento",
  "Fraunces",
  "GFS Neohellenic",
  "Gelasio",
  "Gentium Basic",
  "Gentium Book Basic",
  "Geo",
  "Georama",
  "Glory",
  "Grandstander",
  "Grenze",
  "Gudea",
  "IBM Plex Mono",
  "IBM Plex Sans",
  "IBM Plex Sans Condensed",
  "IBM Plex Serif",
  "IM Fell DW Pica",
  "IM Fell Double Pica",
  "IM Fell English",
  "IM Fell French Canon",
  "IM Fell Great Primer",
  "Ibarra Real Nova",
  "Inria Sans",
  "Inria Serif",
  "Istok Web",
  "JetBrains Mono",
  "Josefin Sans",
  "Josefin Slab",
  "Jost",
  "Judson",
  "K2D",
  "Kanit",
  "Karla",
  "KoHo",
  "Kodchasan",
  "Krub",
  "Kufam",
  "Kulim Park",
  "Lato",
  "Lekton",
  "Libre Baskerville",
  "Libre Caslon Text",
  "Libre Franklin",
  "Linden Hill",
  "Literata",
  "Livvic",
  "Lobster Two",
  "Lora",
  "Mali",
  "Manuale",
  "Marvel",
  "Mate",
  "Merriweather",
  "Merriweather Sans",
  "Montserrat",
  "Montserrat Alternates",
  "Mulish",
  "Neuton",
  "Newsreader",
  "Niramit",
  "Nobile",
  "Noticia Text",
  "Noto Sans",
  "Noto Sans Display",
  "Noto Serif",
  "Noto Serif Display",
  "Noto Serif Tamil",
  "Nunito",
  "Nunito Sans",
  "Old Standard TT",
  "Open Sans",
  "Oregano",
  "Overlock",
  "Overpass",
  "PT Sans",
  "PT Serif",
  "PT Serif Caption",
  "Petrona",
  "Philosopher",
  "Piazzolla",
  "Playfair Display",
  "Playfair Display SC",
  "Poly",
  "Poppins",
  "Prompt",
  "Proza Libre",
  "Public Sans",
  "Puritan",
  "Quantico",
  "Quattrocento Sans",
  "Radley",
  "Raleway",
  "Rambla",
  "Rasa",
  "Red Hat Display",
  "Red Hat Text",
  "Roboto",
  "Roboto Condensed",
  "Roboto Mono",
  "Ropa Sans",
  "Rosario",
  "Rosarivo",
  "Rubik",
  "STIX Two Text",
  "Saira",
  "Sanchez",
  "Sansita",
  "Sarabun",
  "Scada",
  "Share",
  "Simonetta",
  "Sorts Mill Goudy",
  "Source Code Pro",
  "Source Sans Pro",
  "Source Serif Pro",
  "Space Mono",
  "Spectral",
  "Spectral SC",
  "Taviraj",
  "Texturina",
  "Thasadith",
  "Tinos",
  "Titillium Web",
  "Tomorrow",
  "Tourney",
  "Trirong",
  "Trochut",
  "Ubuntu",
  "Ubuntu Mono",
  "Unna",
  "Urbanist",
  "Volkhov",
  "Vollkorn",
  "Work Sans",
  "Xanh Mono",
  "Yrsa",
  "Zen Loop",
  "Zilla Slab"
];